Feature/update prison api client for expire cache
ministryofjustice/hmpps-launchpad-auth pull request #31
Opened 2024-02-08 09:57 UTC by varunkumar139

2024-02-09 14:58 UTC, tosin-ogunrinde requested changes

2024-02-09 14:58 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/config/CacheConfig.kt
>    }
We should consider adding `EventType.EVICTED `and `EventType.REMOVED` to the list of listeners, or at least add `EventType.REMOVED`.

When we call `cache.clear()` the last entry in the cache is removed, and any other entry before the last are evicted. Adding `EventType.EVICTED `and `EventType.REMOVED` will enable us to accurately log this.

2024-02-09 15:10 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/integration/prisonerapi/PrisonerApiServiceImpl.kt
> +    logger.info("User establishment: ${establishment.displayName}")
I done it mainly for to find prisoner establishment from query who logged in last 30 min or 1 hour or 24 hour if we need to check for analytics.

2024-02-12 11:54 UTC, tosin-ogunrinde approved these changes

2024-02-12 11:58 UTC, merged