Feature/add user approved client
ministryofjustice/hmpps-launchpad-auth pull request #4
Opened 2023-07-19 08:07 UTC by varunkumar139

2023-07-26 14:55 UTC, tosin-ogunrinde requested changes

2023-07-26 14:55 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SsoLogInService.kt
> +      val userApprovedClientIfExist =   userApprovedClientService
Consistent spacing

2023-07-26 14:55 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SsoLogInService.kt
> +        userApprovedClientService.updateUserApprovedClient(userApprovedClient)
Consider:

```
 if (!(userApprovedClient.scopes.containsAll(ssoRequest.client.scopes) && ssoRequest.client.scopes.containsAll(userApprovedClient.scopes))) {
           // if record exist approval require only when scope varies
           approvalRequired = true
           userApprovedClient.scopes = ssoRequest.client.scopes
         }
          userApprovedClient.lastModifiedDate = LocalDateTime.now(ZoneOffset.UTC)
         userApprovedClientService.updateUserApprovedClient(userApprovedClient)
```

2023-07-26 14:55 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SsoLogInService.kt
> +  fun updateSsoRequestWithUserId(token: String?, state: UUID): Any {
Worth simplifying this method especially the token conditional checks

2023-07-26 14:55 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/UserApprovedClientService.kt
> +      true,
Why are we hardcoding this? Please see suggestion on using inbuilt Spring Page query.

2023-07-26 14:55 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/UserApprovedClientService.kt
> +  }
It may also be worth logging  a warning if userId does not match the expected regex.

2023-07-26 16:30 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/model/UserApprovedClient.kt
> +    Index(name ="ix_user_id_client_id", columnList = "user_id,client_id", unique = true,)
comma is OK with Kotlin otherwise it give code style warning during build thats why you will see number of comma after even last parameter in number of methods

2023-07-27 08:30 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/resource/UserApprovedClientController.kt
> +    @RequestParam("page") page: Int,
default value set in validation method if page is null

2023-07-27 09:11 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/UserApprovedClientService.kt
> +      true,
I meant why are we hardcoding exchausted = true? This is a dynamic attribute that indicates to the caller of the API:

1. If there are still data to be fetched (i.e. exhausted = false). So they can get the next page (i.e. page + 1)
2. If there are no more data to be fetched (i.e. exhausted = true).

2023-07-27 09:24 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/model/UserApprovedClient.kt
> +    Index(name ="ix_user_id_client_id", columnList = "user_id,client_id", unique = true,)
Does that mean the index on `uk.gov.justice.digital.hmpps.hmppslaunchpadauth.model.SsoRequest` needs resolving?

2023-07-27 11:42 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/UserApprovedClientService.kt
> +  }
Log warn added for regex check. This is only required in api calls for get user's clients, revoke user's client. Currently all other places  user id is extracted from token so additional checks may be not required.

2023-07-28 09:19 UTC, tosin-ogunrinde approved these changes

2023-07-28 09:27 UTC, merged