Feature/auth basic bearer token validation and generation
ministryofjustice/hmpps-launchpad-auth pull request #5
Opened 2023-08-08 08:52 UTC by varunkumar139

2023-08-17 19:43 UTC, tosin-ogunrinde requested changes

2023-08-17 19:43 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +      nonce,
access_token does not have a nonce

2023-08-17 19:43 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +        nonce,
refresh_token does not have a nonce

2023-08-17 19:43 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenGenerationAndValidation.kt
> +          .signWith(alg, secret.toByteArray(Charsets.UTF_8))
alg is always SignatureAlgorithm.HS256 consider setting it here.

2023-08-17 21:22 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/resource/UserApprovedClientController.kt
> +    val authenticationInfo = authentication.authenticate(authorization)
These get validated in TokenAuthentication. TokenAuthentication get claim "sub" and "aud" and find client and userapprovedclient.

2023-08-17 21:23 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +      logger.error("Token is not a valid bearer token {}", credential)
This is logging invalid token format

2023-08-17 21:26 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        } catch (e: Exception) {
There is no one specific exception in try.

2023-08-17 21:34 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        validateScopeInClaims(scopes, userApprovedClient.scopes)
I think we should validate scope. Token is using scope in user approved client for access_token and refresh_token so good to have validate scope. It is standard practise to validate all required claims.

2023-08-17 21:37 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        return AuthenticationUserInfo(client.id, client.scopes, userId, userApprovedClient.scopes)
The standard practise is getting user info from token during authentication and pass to service class for authorisation check if required.

2023-08-17 22:07 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +  private var refreshToken: RefreshTokenPayload,
These classes do not have any private variables so variables will be not shared in threads just like controller or service class as singleton. I agree it is better to initiate new Object each time

2023-08-22 12:38 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/Authentication.kt
> +  fun authenticate(credential: String): AuthenticationInfo
I think it is better to get client in service class, service class has been written to retrieve data from db. We just need to build auth information object and pass it to service class. Authentication is checked in controller class.

2023-08-22 14:17 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +      logger.error("Token is not a valid bearer token {}", credential)
This has been removed

2023-08-22 14:22 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +          UUID.fromString(accessTokenId)
The current checks for access token and make sure refresh token cannot be used as auth bearer token.
It checks following:
1. jti is valid UUDI
2. ati is not present in claims
3. Expire time is greater than current time
4. sub and aud is present and aud is a valid uuid and sub is valid user format
5. Scopes is present and it contains only scopes from scope list enum set string values

2023-08-22 14:24 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        validateScopeInClaims(scopes, userApprovedClient.scopes)
This has been updated to just check scope list is a valid from scope enum values.

2023-08-22 14:25 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        return AuthenticationUserInfo(client.id, client.scopes, userId, userApprovedClient.scopes)
As discussed we only pass client id  after successful login

2023-08-22 14:30 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenPayload.kt
> +    payloadClaims["iat"] = LocalDateTime.now(ZoneOffset.UTC).toEpochSecond(ZoneOffset.UTC)
Updated

2023-08-22 14:48 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/model/AuthorizationGrantType.kt
> +      throw IllegalArgumentException(String.format("Invalid grant value %s", value))
We are using ApiException in service class only method called for serving a request and we know the response code to be sent. For others we should avoid ApiException. These exception will get caught in service class.

2023-08-22 14:57 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +      validateRedirectUri(redirectUri, ssoRequest)
updated

2023-08-22 15:01 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +          return generateToken(userId, clientId, userApprovedClient.scopes, nonce, claims)
This line has been updated. Both access and refresh token contains the scopes which is in user approved clients or sso request.

2023-08-22 15:11 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +        validateGrant(grantType, clientId, client)
Yes, these has been added, it make sure jti is valid UUID, ati is not null

2023-08-22 15:19 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenService.kt
> +          return generateToken(userId, clientId, userApprovedClient.scopes, nonce, null)
Yes, the refresh token when expired will need to have response code Http 400  with error ="expire_refresh_token".
This line has been updated.

2023-08-22 15:27 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/TokenPayload.kt
> +    payloadClaims["exp"] = LocalDateTime.now(ZoneOffset.UTC).plusHours(12).toEpochSecond(ZoneOffset.UTC)
If refresh token in query is valid it just take the payloads and pass payload to generate refresh token class which use existing payload to create refresh token and later new accesstoken id ati is updated only. So refresh token received by using /token and refresh token has everything same except ati. If refresh token has expired then app will need to initaite sso again and get code to get tokens.

2023-08-22 15:57 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/authentication/TokenAuthentication.kt
> +        } catch (e: Exception) {
Updated with jwt exception

2023-08-22 16:01 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/token/IdTokenPayload.kt
> +    return buildClaims(booking!!, establishment!!, profile!!, clientId, scopes, nonce)
this is for id token payload

2023-08-25 16:56 UTC, tosin-ogunrinde approved these changes

2023-08-25 16:58 UTC, merged