updating gradle, spring boot and java version
ministryofjustice/hmpps-launchpad-auth pull request #75
Opened 2024-07-22 07:37 UTC by varunkumar139

2024-07-22 10:32 UTC, tosin-ogunrinde requested changes

2024-07-22 10:32 UTC, tosin-ogunrinde commented on Dockerfile
> +FROM --platform=$BUILDPLATFORM eclipse-temurin:21-jdk-jammy AS builder
Should this be:
`FROM --platform=$BUILDPLATFORM eclipse-temurin:21-jre-jammy AS builder`?

2024-07-22 14:12 UTC, varunkumar139 commented on Dockerfile
> +FROM --platform=$BUILDPLATFORM eclipse-temurin:21-jdk-jammy AS builder
updated

2024-07-23 08:51 UTC, tosin-ogunrinde approved these changes

2024-07-23 08:53 UTC, merged