Feature/dev initial deployment
ministryofjustice/hmpps-launchpad-auth pull request #8
Opened 2023-10-31 09:47 UTC by varunkumar139

2023-11-03 09:25 UTC, psoleckimoj approved these changes
LGTM! Only comment is 3 files don't have the last newline so it shows in the PR 🙂

2023-11-03 12:03 UTC, tosin-ogunrinde requested changes

2023-11-03 12:03 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SsoLogInService.kt
> +  // @Value("\${azure.oauth2-url}")
Remove redundant comments

2023-11-03 12:03 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SsoLogInService.kt
> +  // @Value("\${azure.client-id}")
Remove redundant comments

2023-11-03 12:03 UTC, tosin-ogunrinde commented on src/main/resources/application-preprod.yaml
> +  oauth2-base-url: https://login.microsoftonline.com/
Common values like this in application-dev.yml, application-preprod.yml, and application-prod.yml should all be squashed into application.yml

2023-11-08 16:01 UTC, tosin-ogunrinde approved these changes

2023-11-08 16:27 UTC, merged