adding service access request endpoint, sar service class and require…
ministryofjustice/hmpps-launchpad-auth pull request #84
Opened 2024-08-20 08:45 UTC by varunkumar139

…d repository query

2024-09-27 13:28 UTC, tosin-ogunrinde requested changes

2024-09-27 13:28 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/config/HmppsLaunchpadAuthExceptionHandler.kt
> +    log.error(" exception trace {}", e.printStackTrace())
We should only log one exception. Consider the line below:

`log.error("Unexpected exception ${e.message}", e)`

2024-09-27 13:28 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/repository/UserApprovedClientRepository.kt
> +  fun findUserApprovedClientsByUserIdAndCreatedDateIsGreaterThanEqualAndLastModifiedDateIsLessThanEqual(userId: String, createdDate: LocalDateTime, lastModifiedDate: LocalDateTime): List<UserApproved
I don't think we need these. We can use 
`fun findUserApprovedClientsByUserId(userId: String): List<UserApprovedClient>` and filter the response based on the API parameters.

2024-09-27 13:28 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/repository/UserApprovedClientRepository.kt
> +  fun findUserApprovedClientsByUserIdAndCreatedDateIsGreaterThanEqualAndLastModifiedDateIsLessThanEqual(userId: String, createdDate: LocalDateTime, lastModifiedDate: LocalDateTime): List<UserApproved
Also because of indexing

2024-09-27 13:28 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SarService.kt
> +          convertScopes(userApprovedClient.scopes),
We'll decide the correct payload later today or Monday

2024-09-30 11:26 UTC, tosin-ogunrinde requested changes

2024-09-30 11:31 UTC, varunkumar139 commented on build.gradle.kts
>    testImplementation("com.h2database:h2:2.0.204")
There was updated due security scan flagging vulnerability in previous version.

2024-09-30 12:11 UTC, varunkumar139 commented on build.gradle.kts
>    testImplementation("com.h2database:h2:2.0.204")
This was due to security scan, it updated to latest version

2024-09-30 12:12 UTC, varunkumar139 commented on src/main/resources/application.yml
> +    jwt-helper-enabled: false
Removed as not required

2024-09-30 12:12 UTC, varunkumar139 commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SarService.kt
> +  }
I have updated.

2024-09-30 12:46 UTC, tosin-ogunrinde approved these changes

2024-09-30 12:46 UTC, tosin-ogunrinde commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppslaunchpadauth/service/SarService.kt
> +      }
Is this redundant?

2024-09-30 12:46 UTC, merged